from enum import Enum

class Card(Enum):
    DOIS_ESPADAS = ('DOIS_ESPADAS', 2)
    DOIS_PAUS = ('DOIS_PAUS', 2)
    DOIS_COPAS = ('DOIS_COPAS', 2)
    DOIS_OUROS = ('DOIS_OUROS', 2)

    TRES_ESPADAS = ('TRES_ESPADAS', 3)
    TRES_PAUS = ('TRES_PAUS', 3)
    TRES_COPAS = ('TRES_COPAS', 3)
    TRES_OUROS = ('TRES_OUROS', 3)

    QUATRO_ESPADAS = ('QUATRO_ESPADAS', 4)
    QUATRO_PAUS = ('QUATRO_PAUS', 4)
    QUATRO_COPAS = ('QUATRO_COPAS', 4)
    QUATRO_OUROS = ('QUATRO_OUROS', 4)

    CINCO_ESPADAS = ('CINCO_ESPADAS', 5)
    CINCO_PAUS = ('CINCO_PAUS', 5)
    CINCO_COPAS = ('CINCO_COPAS', 5)
    CINCO_OUROS = ('CINCO_OUROS', 5)

    SEIS_ESPADAS = ('SEIS_ESPADAS', 6)
    SEIS_PAUS = ('SEIS_PAUS', 6)
    SEIS_COPAS = ('SEIS_COPAS', 6)
    SEIS_OUROS = ('SEIS_OUROS', 6)

    SETE_ESPADAS = ('SETE_ESPADAS', 7)
    SETE_PAUS = ('SETE_PAUS', 7)
    SETE_COPAS = ('SETE_COPAS', 7)
    SETE_OUROS = ('SETE_OUROS', 7)

    OITO_ESPADAS = ('OITO_ESPADAS', 8)
    OITO_PAUS = ('OITO_PAUS', 8)
    OITO_COPAS = ('OITO_COPAS', 8)
    OITO_OUROS = ('OITO_OUROS', 8)

    NOVE_ESPADAS = ('NOVE_ESPADAS', 9)
    NOVE_PAUS = ('NOVE_PAUS', 9)
    NOVE_COPAS = ('NOVE_COPAS', 9)
    NOVE_OUROS = ('NOVE_OUROS', 9)

    DEZ_ESPADAS = ('DEZ_ESPADAS0', 10)
    DEZ_PAUS = ('DEZ_PAUS0', 10)
    DEZ_COPAS = ('DEZ_COPAS0', 10)
    DEZ_OUROS = ('DEZ_OUROS0', 10)

    VALETE_ESPADAS = ('VALETE_ESPADAS', 10)
    VALETE_PAUS = ('VALETE_PAUS', 10)
    VALETE_COPAS = ('VALETE_COPAS', 10)
    VALETE_OUROS = ('VALETE_OUROS', 10)

    RAINHA_ESPADAS = ('RAINHA_ESPADAS', 10)
    RAINHA_PAUS = ('RAINHA_PAUS', 10)
    RAINHA_COPAS = ('RAINHA_COPAS', 10)
    RAINHA_OUROS = ('RAINHA_OUROS', 10)

    REI_ESPADAS = ('REI_ESPADAS', 10)
    REI_PAUS = ('REI_PAUS', 10)
    REI_COPAS = ('REI_COPAS', 10)
    REI_OUROS = ('REI_OUROS', 10)

    AS_ESPADAS = ('AS_ESPADAS', 11)
    AS_PAUS = ('AS_PAUS', 11)
    AS_COPAS = ('AS_COPAS', 11)
    AS_OUROS = ('AS_OUROS', 11)


    def __init__(self, label, value):
        self.card_name = label
        self.card_value = value
